site_name: Repo-readteam
 
nav:
  - Home: index.md

  - "ğŸ›  Tools":
      - "â€“ Nmap": tools/nmap.md
      - "â€“ LinPEAS": tools/linpeas.md

  - "ğŸ—’ï¸ Notes":
      - "â€“ Reverse Shells": anotaciones/reverse-shells.md
      - "â€“ SUID": anotaciones/suid.md
      - "â€“ Persistence": anotaciones/persistence.md
      - "â€“ Pivoting": anotaciones/pivoting.md

  - <img src="../../images/htb_icon.ico"> Machine HTB":
      - "Machines": htb/machine.md
      - "ğŸ–¥ï¸ Forest": htb/forest.md
      - "ğŸ–¥ï¸ Voleur": htb/voleur.md
      - "ğŸ–¥ï¸ Era": htb/era.md
      - "ğŸ–¥ï¸ Bashed": htb/bashed.md

theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: slate
    - primary: custom 
    - accent: indigo
    
  language: es
  features:
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight

extra:
  generator: false


extra_css:
  - styles/custom.css
 
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: bash
          class: bash
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: powershell
          class: powershell
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
