site_name: Repo-readteam

nav:
  - Home: index.md
  - "ğŸ§° Machine HTB":
      - "â€“ Overview": htb/machine.md
      - "â€“ Forest": htb/forest.md
      - "â€“ Voleur": htb/voleur.md
      - "â€“ Era": htb/era.md
      - "â€“ Bashed": htb/bashed.md
  - "ğŸ›  Tools":
      - "â€“ Nmap": tools/nmap.md
      - "â€“ LinPEAS": tools/linpeas.md
  - "ğŸ—’ï¸ Notes":
      - "â€“ Reverse Shells": anotaciones/reverse-shells.md
      - "â€“ SUID": anotaciones/suid.md
      - "â€“ Persistence": anotaciones/persistence.md
      - "â€“ Pivoting": anotaciones/pivoting.md

extra:
  generator: false
  favicon: images/favicon.png

extra_css:
  - extra.css

theme:
  name: material
  language: es
  custom_dir: overrides
  palette:
    primary: custom
  features:
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.betterem
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - minify:
      minify_html: true